In [0]:
# !pip install tensorflow==1.15

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import pickle

In [3]:
# text=pd.read_csv('/content/mbti_1.csv',index_col='type')
# text=pd.read_csv('/content/drive/My Drive/FYP-JobMatch/Personality_mbti.csv',index_col='type')
text=pd.read_csv('/content/drive/My Drive/IIT/FYP/Personality_mbti_2.csv',index_col='type') 

print(text.shape)
print(text[0:5])
print(text.iloc[2])

(1554, 2)
                                                  posts      Role
type                                                             
ENTP  I'm finding the lack of me in these posts very...  ANALYSTS
INTP  Good one  _____   https://www.youtube.com/watc...  ANALYSTS
INTJ  'Dear INTP,   I enjoyed our conversation the o...  ANALYSTS
ENTJ  You're fired.|||That's another silly misconcep...  ANALYSTS
INTP  'https://www.youtube.com/watch?v=w8-egj0y8Qs||...  ANALYSTS
posts    'Dear INTP,   I enjoyed our conversation the o...
Role                                              ANALYSTS
Name: INTJ, dtype: object


In [50]:
text.index.value_counts()

ENFJ    111
ESTP    107
ENFP    100
ISTJ    100
INTJ    100
ENTJ    100
ISFJ    100
INTP     99
ISTP     98
ISFP     97
INFJ     95
ESFP     93
ENTP     92
ESTJ     91
ESFJ     88
INFP     83
Name: type, dtype: int64

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
labels=text.index.tolist()
print(labels)

['ENTP', 'INTP', 'INTJ', 'ENTJ', 'INTP', 'INTP', 'INTP', 'INFP', 'INFP', 'INTP', 'ENTJ', 'ENTJ', 'ENFP', 'ISFP', 'INTP', 'ENFP', 'ENTJ', 'INTP', 'INTP', 'ENTJ', 'ISFJ', 'INTP', 'ISFJ', 'INTP', 'INTP', 'INTP', 'ENTP', 'INTP', 'ISFP', 'INTP', 'ENTP', 'INTP', 'ISFJ', 'ISTJ', 'INTP', 'ENTP', 'INTP', 'ISFP', 'ISTJ', 'INTP', 'ENTP', 'ESTP', 'INTP', 'INTP', 'ISTP', 'INTP', 'ISFJ', 'INTP', 'INTP', 'ISFP', 'INTP', 'INTP', 'INTP', 'INTP', 'ESTP', 'INTP', 'INTP', 'ISFJ', 'INTP', 'ISTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'ISTP', 'ISTJ', 'INTP', 'INTP', 'INTP', 'ESFP', 'ISFP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'ISFP', 'ISFP', 'ISFP', 'INTP', 'ISTJ', 'ISTJ', 'ISTJ', 'ISFP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'INTP', 'ISFP', 'INTP', 'INTP', 'INTP', 'ISFP', 'ISFJ', 'INTP', 'ISFJ', 'INTP', 'ISFP', 'ESTP', 'ISTJ', 'ISFP', 'ISFP', 'ESTP', 'ISFP', 'ISFP', 'ISFJ', 'ESFP', 'ESTP', 'ISTJ', 'ESTP', 'ISFP', 'ISFP', 'ESFP', 'ISFJ',

In [56]:
labels[10]

'ENTJ'

In [6]:
from sklearn.preprocessing import LabelBinarizer

# One hot encode labels
labels=text.index.tolist()
encoder=LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)
labels=encoder.fit_transform(labels)
labels=np.array(labels)
print(labels[50:55])

[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]]


In [0]:
#mbti_dict={0:'DIPLOMATS',1:'ANALYSTS',2:'SENTINALS',3:'EXPLORERS'}

In [0]:
mbti_dict={0:'ENFJ',1:'ENFP',2:'ENTJ',3:'ENTP',4:'ESFJ',5:'ESFP',6:'ESTJ',7:'ESTP',8:'INFJ',9:'INFP',10:'INTJ',11:'INTP',12:'ISFJ',13:'ISFP',14:'ISFP',15:'ISTP'}

In [0]:
import re

# Function to clean data ... will be useful later
def post_cleaner(post):
    """cleans individual posts`.
    Args:
        post-string
    Returns:
         cleaned up post`.
    """
    # Covert all uppercase characters to lower case
    post = post.lower() 
    
    # Remove |||
    post=post.replace('|||',"") 

    # Remove URLs, links etc
    post = re.sub(r'''(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))''', '', post, flags=re.MULTILINE) 
    # This would have removed most of the links but probably not all 

    # Remove puntuations 
    puncs1=['@','#','$','%','^','&','*','(',')','-','_','+','=','{','}','[',']','|','\\','"',"'",';',':','<','>','/']
    for punc in puncs1:
        post=post.replace(punc,'') 

    puncs2=[',','.','?','!','\n']
    for punc in puncs2:
        post=post.replace(punc,' ') 
    # Remove extra white spaces
    post=re.sub( '\s+', ' ', post ).strip()
    return post

In [0]:
# Clean up posts
# Covert pandas dataframe object to list. I prefer using lists for prepocessing. 
posts=text.posts.tolist()
posts=[post_cleaner(post) for post in posts]

In [54]:
posts[10]

'now im interested but too lazy to go research it because its timeconsuming welcome to the club mate profile picture of yours is soooooooo infp welcome welcome back is it a communist party sorry had to ask alkhemia welcome thats an interesting nickname youve got there btw it sounds to be a female name but clearly has something to do with that fucks with my mind is a no i mean i can drink some red wine just for the taste but thats it not sure if this thread is only replied to by former drug addicts or if the its not that much the difference between online and offline but the difference between talking about serious and nonserious things im the same person irl and online but others perception of that sounds somewhat like me apart from the gossip thing and the interesting part is that the love for gossip changes a lot if it wasnt there id say that hes just a premature entj but this nah i always got away with the things i did from making smelly smoke bombs in high school to political thing

In [11]:

# Count total words
from collections import Counter

word_count=Counter()
for post in posts:
    word_count.update(post.split(" "))
print(len(word_count))
print(word_count)

54656
Counter({'i': 79669, 'to': 48989, 'the': 48801, 'a': 38792, 'and': 38719, 'of': 29134, 'you': 27213, 'that': 23664, 'is': 22545, 'it': 22452, 'in': 20706, 'my': 20000, 'but': 15336, 'for': 15304, 'with': 13752, 'have': 13642, 'me': 13335, 'im': 13041, 'this': 12175, 'be': 11916, 'are': 11808, 'not': 11619, 'like': 11410, 'an': 10415, 'on': 10366, 'as': 9942, 'so': 9436, 'was': 9384, 'if': 9209, 'just': 9085, 'do': 8720, 'dont': 8626, 'what': 8474, 'or': 8426, 'think': 8134, 'about': 8030, 'its': 7982, 'your': 7392, 'people': 7331, 'when': 7161, 'at': 6681, 'can': 6622, 'all': 6449, 'know': 6000, 'more': 5771, 'they': 5719, 'one': 5690, 'really': 5679, 'would': 5452, 'we': 5340, 'get': 5213, 'how': 5078, 'out': 5069, 'he': 5032, 'from': 5006, 'am': 4820, 'because': 4764, 'ive': 4536, 'some': 4422, 'time': 4333, 'very': 4301, 'up': 4279, 'there': 3958, 'them': 3957, 'no': 3949, 'who': 3796, 'being': 3739, 'much': 3700, 'well': 3649, 'feel': 3577, 'too': 3546, 'been': 3466, 'things'

In [12]:
# Size of the vocabulary available to the RNN
vocab_len=len(word_count)
print(vocab_len)

print(len(posts[0]))

54656
6018


In [13]:
# Create a look up table 
vocab = sorted(word_count, key=word_count.get, reverse=True)
# Create your dictionary that maps vocab words to integers here
vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}

posts_ints=[]
for post in posts:
    posts_ints.append([vocab_to_int[word] for word in post.split()])

print(posts_ints[0])
print(len(posts_ints[0]))

[18, 741, 3, 670, 6, 17, 11, 186, 524, 61, 22881, 455, 42, 20, 708, 29, 37, 11, 3, 127, 1101, 232, 14, 390, 17, 5, 12, 1046, 21, 588, 11, 24, 1109, 137, 50, 16, 2, 6134, 231, 22882, 5, 13589, 63, 264, 260, 685, 198, 861, 2, 482, 622, 506, 228, 5840, 103, 43, 10, 603, 92, 50, 6135, 5, 46, 31, 86, 6, 3, 1487, 173, 1, 2837, 100, 2463, 5, 1679, 100, 375, 15, 5308, 7281, 5, 45, 9249, 11601, 19, 670, 6, 1388, 5, 646, 788, 7282, 337, 1529, 294, 1, 1051, 16768, 703, 1529, 718, 21, 376, 1, 1051, 22883, 34, 1188, 94, 23, 3, 2542, 1007, 6, 19, 144, 1, 85, 1004, 8, 1, 32, 239, 11, 3, 1529, 294, 190, 7, 11602, 7, 44, 102, 24, 228, 40, 7, 10299, 55, 4, 828, 14, 4, 279, 5, 4, 586, 1679, 5, 111, 39, 21, 133, 5555, 25, 38, 524, 5, 1973, 38, 16769, 7, 44, 102, 24, 228, 40, 7, 142, 35, 73, 161, 1, 105, 78, 3, 327, 2009, 3140, 896, 525, 40, 4, 339, 91, 869, 823, 5, 869, 3289, 23, 12, 218, 10, 323, 8409, 115, 2, 1193, 4, 1500, 22884, 2789, 1786, 27, 9, 1, 22885, 2293, 16770, 48, 58, 108, 140, 6, 5309, 34, 

In [14]:
posts_lens = Counter([len(x) for x in posts])
print("Zero-length reviews: {}".format(posts_lens[0]))
print("Maximum review length: {}".format(max(posts_lens)))
print("Minimum review length: {}".format(min(posts_lens)))

seq_len = 500
features=np.zeros((len(posts_ints),seq_len),dtype=int)
for i, row in enumerate(posts_ints):
    features[i, -len(row):] = np.array(row)[:seq_len]
print(features[:10])

Zero-length reviews: 0
Maximum review length: 9588
Minimum review length: 5
[[   18   741     3 ...     3  1644  4391]
 [   74    47   404 ...    25  2091    74]
 [  595   189     1 ...   102    86     6]
 ...
 [    1    35    50 ...     6     3 16829]
 [  103   692    10 ... 23051    77    15]
 [ 5118  1145    28 ...    34     3   567]]


In [0]:
# save the preprocessed data
pickle.dump((features,vocab_to_int,word_count,labels), open('preprocess.p', 'wb'))

In [0]:
# Load preprocessed data
(features,vocab_to_int,word_count,labels)=pickle.load(open('preprocess.p', mode='rb'))

In [17]:

# Split data into training, test and validation

split_frac = 0.8

num_ele=int(split_frac*len(features))
rem_ele=len(features)-num_ele
train_x, val_x = features[:num_ele],features[num_ele:int(rem_ele/2)+num_ele]
train_y, val_y = labels[:num_ele],labels[num_ele:int(rem_ele/2)+num_ele]

test_x =features[num_ele+int(rem_ele/2):]
test_y = labels[num_ele+int(rem_ele/2):]

print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(1243, 500) 
Validation set: 	(155, 500) 
Test set: 		(156, 500)


In [0]:
lstm_size = 256
lstm_layers = 1
batch_size = 150
learning_rate = 0.01
embed_dim=250

In [0]:
#pip install --upgrade tensorboard

In [0]:
n_words = len(vocab_to_int) + 1 # Adding 1 because we use 0's for padding, dictionary started at 1
#1.disable_v2_behavior()
# Create the graph object
graph = tf.Graph()
# Add nodes to the graph
with graph.as_default():
    input_data = tf.placeholder(tf.int32, [None, None], name='inputs')
    labels_ = tf.placeholder(tf.int32, [None, None], name='labels')
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')

In [36]:
# Embedding
with graph.as_default():
    embedding= tf.Variable(tf.random_uniform(shape=(n_words,embed_dim),minval=-1,maxval=1))
    embed=tf.nn.embedding_lookup(embedding,input_data)
    print(embed.shape)

(?, ?, 250)


In [0]:
#import tensorflow_addons as tfa
#LSTM cell
with graph.as_default():
#tf.Graph
  # basic LSTM cell
  lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
      
  # Add dropout to the cell
  drop = tf.contrib.rnn.DropoutWrapper(lstm,output_keep_prob=keep_prob)
      
  # Stack up multiple LSTM layers, for deep learning
  cell = tf.contrib.rnn.MultiRNNCell([drop]* lstm_layers)
      
  # Getting an initial state of all zeros
  initial_state = cell.zero_state(batch_size, tf.float32)

In [38]:
print(tf.__version__)

1.15.0


In [0]:
with graph.as_default():
    outputs,final_state=tf.nn.dynamic_rnn(cell,embed,dtype=tf.float32 )

In [0]:
with graph.as_default():  
    pre = tf.layers.dense(outputs[:,-1], 16, activation=tf.nn.relu)
    predictions=tf.layers.dense(pre, 16, activation=tf.nn.softmax)
    
    cost = tf.losses.mean_squared_error(labels_, predictions)
    optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [0]:
with graph.as_default():
    correct_pred = tf.equal(tf.cast(tf.round(predictions), tf.int32), labels_)
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

In [0]:
def get_batches(x, y, batch_size=100):
    
    n_batches = len(x)//batch_size
    x, y = x[:n_batches*batch_size], y[:n_batches*batch_size]
    for ii in range(0, len(x), batch_size):
        yield x[ii:ii+batch_size], y[ii:ii+batch_size]

In [43]:
epochs = 3

with graph.as_default():
    saver = tf.train.Saver()

with tf.Session(graph=graph) as sess:
    sess.run(tf.global_variables_initializer())
    iteration = 1
    for e in range(epochs):
        state = sess.run(initial_state)
        
        for ii, (x, y) in enumerate(get_batches(train_x, train_y, batch_size), 1):
            feed = {input_data: x,
                    labels_: y,
                    keep_prob: 1.0,
                    initial_state: state}
            loss, state, _ = sess.run([cost, final_state, optimizer], feed_dict=feed)
            
            if iteration%5==0:
                print("Epoch: {}/{}".format(e, epochs),
                      "Iteration: {}".format(iteration),
                      "Train loss: {:.3f}".format(loss))

            if iteration%25==0:
                val_acc = []
                val_state = sess.run(cell.zero_state(batch_size, tf.float32))
                for x, y in get_batches(val_x, val_y, batch_size):
                    feed = {input_data: x,
                            labels_: y,
                            keep_prob: 1,
                            initial_state: val_state}
                    batch_acc, val_state = sess.run([accuracy, final_state], feed_dict=feed)
                    val_acc.append(batch_acc)
                print("Val acc: {:.3f}".format(np.mean(val_acc)))
            iteration +=1
    saver.save(sess, "checkpoints/mbti.ckpt")

Epoch: 0/3 Iteration: 5 Train loss: 0.058
Epoch: 1/3 Iteration: 10 Train loss: 0.057
Epoch: 1/3 Iteration: 15 Train loss: 0.055
Epoch: 2/3 Iteration: 20 Train loss: 0.050


In [0]:
labels=text.index.tolist()

In [71]:
test_acc = []
prediction = ''
with tf.Session(graph=graph) as sess:
    saver.restore(sess, tf.train.latest_checkpoint('checkpoints'))
    test_state = sess.run(cell.zero_state(batch_size, tf.float32))
    for ii, (x, y) in enumerate(get_batches(test_x, test_y, batch_size), 1):
        feed = {input_data: x,
                labels_: y,
                keep_prob: 1,
                initial_state: test_state}
        batch_acc, test_state = sess.run([accuracy, final_state], feed_dict=feed)
        test_acc.append(batch_acc)
        # # prediction 
        prediction = sess.run(predictions, feed_dict=feed)
    print("Test accuracy: {:.3f}".format(np.mean(test_acc)))
    print(prediction)
    best_guess = np.argmax(prediction) 
    print(best_guess)
    # labels = ['entertainment', 'bussiness', 'science/tech', 'health']
    print(labels[np.argmax(prediction)])

INFO:tensorflow:Restoring parameters from checkpoints/mbti.ckpt
Test accuracy: 0.937
[[0.04696098 0.05264699 0.06908986 ... 0.0072755  0.02834649 0.02044737]
 [0.08335639 0.05170909 0.03985246 ... 0.03692348 0.02391501 0.02807477]
 [0.05412479 0.04517766 0.03044259 ... 0.01504726 0.09328384 0.02359826]
 ...
 [0.08717911 0.07374325 0.0498387  ... 0.03658068 0.0181335  0.05533697]
 [0.04553095 0.05008003 0.05751268 ... 0.0184089  0.08854536 0.03145916]
 [0.06483223 0.01293346 0.12270916 ... 0.00960593 0.14836173 0.00901228]]
650
ISTP


In [0]:
def predict(textArr):
    # input_text = ['It has been too long since I have been on personalitycafe although it doesnt seem to have changed one bit - but I must say it is good to be back somewhere like this. Usually I turn to Doctor Who']
    input_text = textArr

    # Count total words
    from collections import Counter

    word_count2=Counter()
    for it in input_text:
        word_count2.update(it.split(" "))

    vocab_len2=len(word_count2)


    vocab2 = sorted(word_count2, key=word_count2.get, reverse=True)
    # Create your dictionary that maps vocab words to integers here
    vocab_to_int2 = {word2: ii for ii, word2 in enumerate(vocab2, 1)}

    posts_ints2=[]
    for post2 in input_text:
        posts_ints2.append([vocab_to_int2[word2] for word2 in post2.split()])

    seq_len = 500
    features2=np.zeros((len(posts_ints2),seq_len),dtype=int)
    for i, row in enumerate(posts_ints2):
        features2[i, -len(row):] = np.array(row)[:seq_len]
    # print(features2[:10])

    pred = ''
    with tf.Session(graph=graph) as sess:
        saver.restore(sess, tf.train.latest_checkpoint('checkpoints'))
        test_state = sess.run(cell.zero_state(batch_size, tf.float32))
        # for ii, (x, y) in enumerate(get_batches(test_x2, test_y, batch_size), 1):
        feed = {input_data: features2,
                keep_prob: 1,
                initial_state: test_state}
        # # prediction 
        pred = sess.run(predictions, feed_dict=feed)
        print(pred)
        best_guess = np.argmax(pred) 
        print(best_guess)
        # labels = ['entertainment', 'bussiness', 'science/tech', 'health']
        predi = labels[np.argmax(pred)]

    return predi

In [73]:
predic = predict(["surprising anyways im happy to be here at least"])
print(predic)

INFO:tensorflow:Restoring parameters from checkpoints/mbti.ckpt
[[0.06731322 0.10223038 0.03628028 0.01423456 0.00075309 0.01574071
  0.0126104  0.01782096 0.16536322 0.03669782 0.01717362 0.01111099
  0.281644   0.04268099 0.00351322 0.17483255]]
12
ENFP
